from typing import Any, Callable, Dict, List, Optional, Sequence

class StepResult:
    event: Dict[str, Any]
    audio: List[Dict[str, Any]]

class ResourceConfig:
    def __init__(
        self, max_texture_memory: int = ..., max_script_bytes: int = ...
    ) -> None: ...

class AudioController:
    def play_bgm(self, asset: str, loop: bool = ..., fade_in: float = ...) -> None: ...
    def stop_all(self, fade_out: float = ...) -> None: ...
    def play_sfx(self, asset: str) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Engine:
    def __init__(self, script_json: str) -> None: ...
    def current_event(self) -> Dict[str, Any]: ...
    def visual_state(self) -> Dict[str, Any]: ...
    def step(self) -> StepResult: ...
    def choose(self, option_index: int) -> StepResult: ...
    def resume(self) -> StepResult: ...
    def supported_event_types(self) -> List[str]: ...
    def set_resources(self, config: ResourceConfig) -> None: ...
    def get_memory_usage(self) -> Dict[str, int]: ...
    def allow_ext_call_command(self, command: str) -> None: ...
    def register_handler(self, handler: Callable[[str, List[str]], Any]) -> None: ...
    def last_ext_call_error(self) -> Optional[str]: ...
    def set_prefetch_depth(self, depth: int) -> None: ...
    def prefetch_assets_hint(self) -> List[str]: ...
    def is_loading(self) -> bool: ...
    def audio(self) -> AudioController: ...
    def is_current_dialogue_read(self) -> bool: ...
    def choice_history(self) -> List[Dict[str, Any]]: ...
    def __getattr__(self, name: str) -> Any: ...

class PyEngine(Engine): ...

class StoryNode:
    @classmethod
    def start(cls) -> "StoryNode": ...
    @classmethod
    def end(cls) -> "StoryNode": ...
    @classmethod
    def dialogue(cls, speaker: str, text: str) -> "StoryNode": ...
    @classmethod
    def scene(
        cls,
        background: Optional[str] = ...,
        music: Optional[str] = ...,
        characters: Sequence[Any] = ...,
    ) -> "StoryNode": ...
    @classmethod
    def scene_full(
        cls,
        background: Optional[str] = ...,
        music: Optional[str] = ...,
        characters: Sequence[Any] = ...,
    ) -> "StoryNode": ...
    @classmethod
    def choice(cls, prompt: str, options: Sequence[str]) -> "StoryNode": ...
    @classmethod
    def set_flag(cls, key: str, value: bool) -> "StoryNode": ...
    @classmethod
    def jump_if_flag(cls, key: str, is_set: bool, target: str) -> "StoryNode": ...
    @classmethod
    def ext_call(cls, command: str, args: Sequence[str] = ...) -> "StoryNode": ...
    def __getattr__(self, name: str) -> Any: ...

class NodeGraph:
    def __init__(self) -> None: ...
    def add_node(self, node: StoryNode, x: float, y: float) -> int: ...
    def connect(self, from_node: int, to_node: int) -> None: ...
    def connect_port(self, from_node: int, from_port: int, to_node: int) -> None: ...
    def connect_or_branch(
        self, from_node: int, from_port: int, to_node: int
    ) -> bool: ...
    def node_count(self) -> int: ...
    def connection_count(self) -> int: ...
    def save(self, path: str) -> None: ...
    @classmethod
    def load(cls, path: str) -> "NodeGraph": ...
    @classmethod
    def from_script_json(cls, script_json: str) -> "NodeGraph": ...
    def to_script_json(self) -> str: ...
    def connections(self) -> List[Dict[str, Any]]: ...
    def __getattr__(self, name: str) -> Any: ...

class ScriptBuilder:
    def supported_event_types(self) -> List[str]: ...
    def __getattr__(self, name: str) -> Any: ...

class GraphStats:
    total_nodes: int
    reachable_nodes: int
    unreachable_nodes: int
    dialogue_count: int
    choice_count: int
    branch_count: int
    edge_count: int

class GraphNode:
    id: int
    node_type: str
    details: str
    labels: List[str]
    reachable: bool

class GraphEdge:
    from_id: int
    to_id: int
    edge_type: str
    label: Optional[str]

class StoryGraph:
    @classmethod
    def from_json(cls, script_json: str) -> "StoryGraph": ...
    def stats(self) -> GraphStats: ...
    def unreachable_nodes(self) -> List[int]: ...
    def nodes(self) -> List[GraphNode]: ...
    def edges(self) -> List[GraphEdge]: ...
    def find_by_label(self, label: str) -> Optional[int]: ...
    def to_dot(self) -> str: ...
    def __getattr__(self, name: str) -> Any: ...

class Keyframe:
    def __init__(self, time: int, value: int, easing: str = ...) -> None: ...

class Track:
    def __init__(self, entity_id: int, property: str) -> None: ...
    def add_keyframe(self, keyframe: Keyframe) -> None: ...
    def keyframes(self) -> List[Keyframe]: ...

class Timeline:
    duration: int
    def __init__(self, ticks_per_second: int = ...) -> None: ...
    def add_track(self, track: Track) -> None: ...
    def __len__(self) -> int: ...
    def evaluate_at(self, time: int) -> Dict[str, Any]: ...
    def seek(self, time: int) -> None: ...
    def advance(self, ticks: int) -> None: ...
    def evaluate(self) -> Dict[str, Any]: ...

def py_validate_graph(graph: NodeGraph) -> List[Any]: ...
def __getattr__(name: str) -> Any: ...
