from typing import Any, Callable, Dict, List, NoReturn, Optional, Sequence

class _JsonBacked:
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class ExportPlan(_JsonBacked): ...
class ExportReport(_JsonBacked): ...
class RouteTree(_JsonBacked): ...
class SceneFrame(_JsonBacked): ...
class UiThemeValidationReport(_JsonBacked): ...
class LayoutResolution(_JsonBacked): ...
class VnError(Exception): ...
class VnValidationError(VnError): ...
class VnSecurityPolicyError(VnError): ...
class VnResourceLimitError(VnError): ...
class VnEndOfScriptError(VnError): ...

class StepResult:
    event: Dict[str, Any]
    audio: List[Dict[str, Any]]

class ResourceConfig:
    def __init__(
        self, max_texture_memory: int = ..., max_script_bytes: int = ...
    ) -> None: ...

class VnConfig:
    def __init__(
        self,
        title: Optional[str] = ...,
        width: Optional[float] = ...,
        height: Optional[float] = ...,
        fullscreen: Optional[bool] = ...,
        scale_factor: Optional[float] = ...,
        assets_root: Optional[str] = ...,
        asset_cache_budget_mb: Optional[int] = ...,
        security_mode: Optional[str] = ...,
        manifest_path: Optional[str] = ...,
        require_manifest: Optional[bool] = ...,
        preferences_path: Optional[str] = ...,
        player_menu_json: Optional[str] = ...,
    ) -> None: ...

class AudioController:
    def play_bgm(
        self,
        asset: str,
        loop: bool = ...,
        fade_in: float = ...,
        volume: Optional[float] = ...,
    ) -> None: ...
    def stop_all(self, fade_out: float = ...) -> None: ...
    def play_sfx(self, asset: str, volume: Optional[float] = ...) -> None: ...
    def play_voice(self, asset: str, volume: Optional[float] = ...) -> None: ...

class Engine:
    def __init__(self, script_json: str) -> None: ...
    def current_event(self) -> Dict[str, Any]: ...
    def current_event_json(self) -> str: ...
    def visual_state(self) -> Dict[str, Any]: ...
    def ui_state(self) -> Dict[str, Any]: ...
    def step(self) -> StepResult: ...
    def choose(self, option_index: int) -> Dict[str, Any]: ...
    def resume(self) -> None: ...
    def supported_event_types(self) -> List[str]: ...
    def set_resources(self, config: ResourceConfig) -> None: ...
    def get_memory_usage(self) -> Dict[str, Any]: ...
    def cache_asset(self, asset_path: str, data: bytes) -> None: ...
    def get_cached_asset(self, asset_path: str) -> Optional[bytes]: ...
    def invalidate_cached_asset(self, asset_path: str) -> bool: ...
    def clear_asset_cache(self) -> None: ...
    def evict_unused_assets(self) -> int: ...
    def asset_cache_stats(self) -> Dict[str, Any]: ...
    def allow_ext_call_command(self, command: str) -> None: ...
    def clear_ext_call_capabilities(self) -> None: ...
    def register_handler(self, handler: Callable[[str, List[str]], Any]) -> None: ...
    def last_ext_call_error(self) -> Optional[str]: ...
    def set_prefetch_depth(self, depth: int) -> None: ...
    def prefetch_depth(self) -> int: ...
    def prefetch_assets_hint(self) -> List[str]: ...
    def is_loading(self) -> NoReturn: ...
    def audio(self) -> AudioController: ...
    def is_current_dialogue_read(self) -> bool: ...
    def choice_history(self) -> List[Dict[str, Any]]: ...
    def route_tree(self) -> RouteTree: ...
    def scene_frame(self) -> SceneFrame: ...
    def get_last_audio_commands(self) -> List[Dict[str, Any]]: ...

class PyEngine(Engine): ...

class StoryNode:
    @classmethod
    def start(cls) -> "StoryNode": ...
    @classmethod
    def end(cls) -> "StoryNode": ...
    @classmethod
    def dialogue(cls, speaker: str, text: str) -> "StoryNode": ...
    @classmethod
    def scene(
        cls,
        background: Optional[str] = ...,
        music: Optional[str] = ...,
        characters: Sequence[Any] = ...,
    ) -> "StoryNode": ...
    @classmethod
    def scene_full(
        cls,
        background: Optional[str] = ...,
        music: Optional[str] = ...,
        characters: Sequence[Any] = ...,
    ) -> "StoryNode": ...
    @classmethod
    def choice(cls, prompt: str, options: Sequence[str]) -> "StoryNode": ...
    @classmethod
    def set_flag(cls, key: str, value: bool) -> "StoryNode": ...
    @classmethod
    def set_variable(cls, key: str, value: int) -> "StoryNode": ...
    @classmethod
    def jump(cls, target: str) -> "StoryNode": ...
    @classmethod
    def jump_if_flag(cls, key: str, is_set: bool, target: str) -> "StoryNode": ...
    @classmethod
    def jump_if_var(cls, key: str, op: str, value: int, target: str) -> "StoryNode": ...
    @classmethod
    def scene_patch(
        cls,
        background: Optional[str] = ...,
        music: Optional[str] = ...,
        add: Sequence[Any] = ...,
        update: Sequence[Any] = ...,
        remove: Sequence[str] = ...,
    ) -> "StoryNode": ...
    @classmethod
    def scene_patch_full(
        cls,
        background: Optional[str] = ...,
        music: Optional[str] = ...,
        add: Sequence[Any] = ...,
        update: Sequence[Any] = ...,
        remove: Sequence[str] = ...,
    ) -> "StoryNode": ...
    @classmethod
    def audio_action(
        cls,
        channel: str,
        action: str,
        asset: Optional[str] = ...,
        volume: Optional[float] = ...,
        fade_duration_ms: Optional[int] = ...,
        loop_playback: Optional[bool] = ...,
    ) -> "StoryNode": ...
    @classmethod
    def transition(
        cls, kind: str, duration_ms: int, color: Optional[str] = ...
    ) -> "StoryNode": ...
    @classmethod
    def character_placement(
        cls, name: str, x: int, y: int, scale: Optional[float] = ...
    ) -> "StoryNode": ...
    @classmethod
    def subgraph_call(
        cls,
        fragment_id: str,
        entry_port: Optional[str] = ...,
        exit_port: Optional[str] = ...,
    ) -> "StoryNode": ...
    @classmethod
    def generic(cls, event_json: str) -> "StoryNode": ...
    @classmethod
    def ext_call(cls, command: str, args: Sequence[str] = ...) -> "StoryNode": ...

class NodeGraph:
    def __init__(self) -> None: ...
    def add_node(self, node: StoryNode, x: float, y: float) -> int: ...
    def connect(self, from_node: int, to_node: int) -> None: ...
    def connect_port(self, from_node: int, from_port: int, to_node: int) -> None: ...
    def connect_new_choice_option(
        self, choice_id: int, to_id: int, text: str = ...
    ) -> bool: ...
    def connect_or_branch(
        self,
        from_node: int,
        from_port: int,
        to_node: int,
        branch_x: Optional[float] = ...,
        branch_y: Optional[float] = ...,
    ) -> bool: ...
    def remove_node(self, node_id: int) -> None: ...
    def node_count(self) -> int: ...
    def connection_count(self) -> int: ...
    def node_ids(self) -> List[int]: ...
    def get_node(self, node_id: int) -> Optional[StoryNode]: ...
    def node_position(self, node_id: int) -> Optional[Any]: ...
    def nodes(self) -> List[Any]: ...
    def is_empty(self) -> bool: ...
    def save(self, path: str) -> None: ...
    @classmethod
    def load(cls, path: str) -> "NodeGraph": ...
    @classmethod
    def from_script_json(cls, script_json: str) -> "NodeGraph": ...
    @classmethod
    def from_authoring_or_script_json(cls, source: str) -> "NodeGraph": ...
    def to_script_json(self) -> str: ...
    def to_lossy_script_json_for_diagnostics(self) -> str: ...
    def validate_no_io(self) -> List["LintIssue"]: ...
    def validate(self, project_root: Optional[str] = ...) -> List["LintIssue"]: ...
    def validation_report(
        self, project_root: Optional[str] = ...
    ) -> "AuthoringValidationReport": ...
    def connections(self) -> List[Any]: ...
    def search_nodes(self, query: str) -> List[int]: ...
    def create_fragment(
        self, fragment_id: str, title: str, node_ids: Sequence[int]
    ) -> bool: ...
    def remove_fragment(self, fragment_id: str) -> bool: ...
    def list_fragments(self) -> List["GraphFragment"]: ...
    def get_fragment(self, fragment_id: str) -> Optional["GraphFragment"]: ...
    def enter_fragment(self, fragment_id: str) -> bool: ...
    def leave_fragment(self) -> bool: ...
    def active_fragment(self) -> Optional[str]: ...
    def fragment_ports(self, fragment_id: str) -> List["FragmentPort"]: ...
    def refresh_fragment_ports(self, fragment_id: str) -> bool: ...
    def validate_fragments(self) -> List["LintIssue"]: ...
    def operation_log(self) -> List["OperationLogEntry"]: ...
    def verification_runs(self) -> List["VerificationRun"]: ...
    def compose_scene_snapshot(
        self,
        selected_node_id: Optional[int] = ...,
        stage_width: Optional[int] = ...,
        stage_height: Optional[int] = ...,
        locale: Optional[str] = ...,
    ) -> "ComposerSnapshot": ...
    def list_layered_objects(
        self, selected_node_id: Optional[int] = ...
    ) -> List["LayeredSceneObject"]: ...
    def list_stage_layers(self) -> List[str]: ...
    def set_layer_visible(self, object_id: str, visible: bool) -> None: ...
    def set_layer_locked(self, object_id: str, locked: bool) -> None: ...
    def move_scene_object(
        self, object_id: str, x: int, y: int, scale: Optional[float] = ...
    ) -> bool: ...
    def edit_dialogue(self, node_id: int, speaker: str, text: str) -> bool: ...
    def edit_choice_prompt(self, node_id: int, prompt: str) -> bool: ...
    def edit_choice_option_text(
        self, node_id: int, option_index: int, text: str
    ) -> bool: ...
    def reorder_choice_option(
        self, node_id: int, from_index: int, to_index: int
    ) -> bool: ...
    def set_choice_option_target(
        self, node_id: int, option_index: int, target_node_id: int
    ) -> bool: ...
    def preview_start_from_node(self, node_id: int) -> "ComposerPreviewSession": ...
    def fix_candidates(self, issue_index: int) -> List["QuickFixCandidate"]: ...
    def autofix_issue(self, issue_index: int, include_review: bool = ...) -> bool: ...
    def autofix_safe(self) -> int: ...
    def autofix_full(self) -> int: ...
    def set_bookmark(self, name: str, node_id: int) -> bool: ...
    def remove_bookmark(self, name: str) -> bool: ...
    def bookmark_target(self, name: str) -> Optional[int]: ...
    def list_bookmarks(self) -> List[Any]: ...

class ScriptBuilder:
    def __init__(self) -> None: ...
    def label(self, name: str) -> None: ...
    def supported_event_types(self) -> List[str]: ...
    def dialogue(self, speaker: str, text: str) -> None: ...
    def choice(self, prompt: str, options: Sequence[Any]) -> None: ...
    def scene(
        self,
        background: Optional[str] = ...,
        music: Optional[str] = ...,
        characters: Sequence[Any] = ...,
    ) -> None: ...
    def patch(
        self,
        background: Optional[str] = ...,
        music: Optional[str] = ...,
        add: Sequence[Any] = ...,
        update: Sequence[Any] = ...,
        remove: Sequence[str] = ...,
    ) -> None: ...
    def audio_action(
        self,
        channel: str,
        action: str,
        asset: Optional[str] = ...,
        volume: Optional[float] = ...,
        fade_duration_ms: Optional[int] = ...,
        loop_playback: Optional[bool] = ...,
    ) -> None: ...
    def transition(
        self, kind: str, duration_ms: int, color: Optional[str] = ...
    ) -> None: ...
    def set_character_position(
        self, name: str, x: int, y: int, scale: Optional[float] = ...
    ) -> None: ...
    def jump(self, target: str) -> None: ...
    def set_flag(self, key: str, value: bool) -> None: ...
    def set_var(self, key: str, value: int) -> None: ...
    def jump_if_flag(self, key: str, is_set: bool, target: str) -> None: ...
    def jump_if_var(self, key: str, op: str, value: int, target: str) -> None: ...
    def ext_call(self, command: str, args: Sequence[str]) -> None: ...
    def build_json(self) -> str: ...

class GraphStats:
    total_nodes: int
    reachable_nodes: int
    unreachable_nodes: int
    dialogue_count: int
    choice_count: int
    branch_count: int
    edge_count: int

class GraphNode:
    id: int
    node_type: str
    details: str
    labels: List[str]
    reachable: bool

class GraphEdge:
    from_id: int
    to_id: int
    edge_type: str
    label: Optional[str]

class StoryGraph:
    @classmethod
    def from_json(cls, script_json: str) -> "StoryGraph": ...
    def stats(self) -> GraphStats: ...
    def unreachable_nodes(self) -> List[int]: ...
    def nodes(self) -> List[GraphNode]: ...
    def edges(self) -> List[GraphEdge]: ...
    def find_by_label(self, label: str) -> Optional[int]: ...
    def to_dot(self) -> str: ...

class Keyframe:
    def __init__(self, time: int, value: int, easing: str = ...) -> None: ...

class Track:
    def __init__(self, entity_id: int, property: str) -> None: ...
    def add_keyframe(self, keyframe: Keyframe) -> None: ...
    def remove_keyframe(self, time: int) -> None: ...
    def keyframes(self) -> List[Keyframe]: ...
    def evaluate(self, time: int) -> Dict[str, Any]: ...
    def is_empty(self) -> bool: ...

class Timeline:
    duration: int
    def __init__(self, ticks_per_second: int = ...) -> None: ...
    def add_track(self, track: Track) -> None: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def evaluate_at(self, time: int) -> Dict[str, Any]: ...
    def seek(self, time: int) -> None: ...
    def advance(self, ticks: int) -> None: ...
    def evaluate(self) -> Dict[str, Any]: ...

class QuickFixCandidate:
    fix_id: str
    label: str
    description: str
    risk: str
    structural: bool

class LintSeverity:
    Error: "LintSeverity"
    Warning: "LintSeverity"
    Info: "LintSeverity"

class _JsonRoundtrip:
    def to_json(self) -> str: ...

class DiagnosticTarget(_JsonRoundtrip):
    @classmethod
    def from_json(cls, source: str) -> "DiagnosticTarget": ...

class FieldPath(_JsonRoundtrip):
    @classmethod
    def from_json(cls, source: str) -> "FieldPath": ...

class SemanticValue(_JsonRoundtrip):
    @classmethod
    def from_json(cls, source: str) -> "SemanticValue": ...

class EvidenceTrace(_JsonRoundtrip):
    @classmethod
    def from_json(cls, source: str) -> "EvidenceTrace": ...

class TraceAtom(_JsonRoundtrip):
    @classmethod
    def from_json(cls, source: str) -> "TraceAtom": ...

class TraceEdge(_JsonRoundtrip):
    @classmethod
    def from_json(cls, source: str) -> "TraceEdge": ...

class OperationStatus(_JsonRoundtrip):
    @classmethod
    def from_json(cls, source: str) -> "OperationStatus": ...

class OperationLogEntry(_JsonRoundtrip):
    @classmethod
    def from_json(cls, source: str) -> "OperationLogEntry": ...

class VerificationRun(_JsonRoundtrip):
    @classmethod
    def from_json(cls, source: str) -> "VerificationRun": ...

class GraphFragment(_JsonRoundtrip):
    fragment_id: str
    title: str
    node_ids: List[int]
    inputs: List[Any]
    outputs: List[Any]
    @classmethod
    def from_json(cls, source: str) -> "GraphFragment": ...

class FragmentPort(_JsonRoundtrip):
    node_id: int
    port_id: int
    label: str
    @classmethod
    def from_json(cls, source: str) -> "FragmentPort": ...

class LintIssue:
    def localized(self, locale: Optional[str] = ...) -> Dict[str, Any]: ...

class LayeredSceneObject:
    object_id: str
    layer_id: str
    source_node_id: Optional[int]
    source_field_path: str
    asset_path: Optional[str]
    character_name: Optional[str]
    expression: Optional[str]
    x: Optional[int]
    y: Optional[int]
    scale: Optional[float]
    z_index: int
    visible: bool
    locked: bool
    kind: str
    def to_json(self) -> str: ...

class ComposerSnapshot:
    schema: str
    stage_width: int
    stage_height: int
    objects: List[LayeredSceneObject]
    overlays_json: List[str]
    @classmethod
    def from_json(cls, source: str) -> "ComposerSnapshot": ...
    def to_json(self) -> str: ...

class ComposerPreviewSession:
    def advance(self) -> None: ...
    def choose(self, option_index: int) -> None: ...
    def snapshot(
        self, selected_node_id: Optional[int] = ..., runtime_mode: bool = ...
    ) -> ComposerSnapshot: ...

class AuthoringValidationReport:
    schema: str
    issue_count: int
    error_count: int
    warning_count: int
    info_count: int
    diagnostic_ids: List[str]

    @classmethod
    def from_json(cls, source: str) -> "AuthoringValidationReport": ...
    def to_json(self) -> str: ...
    def issues(self) -> List[str]: ...
    def issues_json(self) -> str: ...
    def explain(self, diagnostic_id: str) -> Optional[str]: ...
    def fingerprints_json(self) -> str: ...
    def is_stale_against(self, current_fingerprints_json: str) -> bool: ...
    def is_stale_against_report(self, current: "AuthoringValidationReport") -> bool: ...

def py_validate_graph(graph: NodeGraph) -> List[LintIssue]: ...
def validate_runtime_config(
    script_json: str, config: Optional["VnConfig"] = ...
) -> None: ...
def validate_script_schema_version(
    script_schema_version: Optional[str] = ..., policy: str = ...
) -> str: ...
def run_visual_novel(
    script_json: str, config: Optional["VnConfig"] = ...
) -> NoReturn: ...
def export_bundle(
    project_root: str,
    output_root: str,
    entry_script: Optional[str] = ...,
    target: str = ...,
    runtime_artifact: Optional[str] = ...,
    require_executable: bool = ...,
    integrity: str = ...,
    hmac_key: Optional[str] = ...,
    layout_version: int = ...,
) -> ExportReport: ...
def export_bundle_json(
    project_root: str,
    output_root: str,
    entry_script: Optional[str] = ...,
    target: str = ...,
    runtime_artifact: Optional[str] = ...,
    require_executable: bool = ...,
    integrity: str = ...,
    hmac_key: Optional[str] = ...,
    layout_version: int = ...,
) -> str: ...
def plan_export(
    project_root: str,
    output_root: str,
    entry_script: Optional[str] = ...,
    target: str = ...,
    runtime_artifact: Optional[str] = ...,
    integrity: str = ...,
    hmac_key: Optional[str] = ...,
    layout_version: int = ...,
) -> ExportPlan: ...
def default_player_menu_config() -> str: ...
def validate_player_menu_config(config_json: str) -> str: ...
def validate_ui_theme(theme_json: str) -> UiThemeValidationReport: ...
def resolve_layout(
    display_json: str,
    stage_json: Optional[str] = ...,
    policy_json: Optional[str] = ...,
) -> LayoutResolution: ...
