manifest_schema_version = "1.0"

[metadata]
name = "Demo Story"
author = "User"
version = "0.1.0"
description = "A demo visual novel project"

[settings]
resolution = [
    1280,
    720,
]
default_language = "en"
supported_languages = ["en"]
entry_point = "demo_story.json"

[assets.backgrounds]
genshin-furina_6 = 'assets\backgrounds\genshin-furina-6.png'
genshin-furina = 'assets\backgrounds\genshin-furina.png'
genshin-furina_1 = 'assets\backgrounds\genshin-furina-1.png'
genshin-furina_2 = 'assets\backgrounds\genshin-furina-2.png'
genshin-furina_4 = 'assets\backgrounds\genshin-furina-4.png'
genshin-furina_5 = 'assets\backgrounds\genshin-furina-5.png'
genshin-furina_3 = 'assets\backgrounds\genshin-furina-3.png'

[assets.characters]

[assets.audio]
2025-11-14-18-36-38 = 'assets\audio\2025-11-14-18-36-38.mp3'
